### ISSUE TITLE
connection refused on different linux distro 

### ISSUE THREAD

**Issue by roelof1967** [hapijs/makemehapi#109] opened 2015-01-06 18:39 UTC
Hello, 

I try to make the first exercise. 
Then I do node hello.js 3456 
and open my browser and goto localhost:3456 and see hello,hapi. 

Then I do makemehapi run hello.js and the first thing I see is this error message: 

✗ Error connecting to http://localhost:14163: ECONNREFUSED                                                                                                                             

Error: connect ECONNREFUSED                                                                                                                                                            
    at errnoException (net.js:904:11)                                                                                                                                                  
    at Object.afterConnect [as oncomplete] (net.js:895:19) 

I do not understand why this happens. 
I do not make any difference if I disable the firewall. 

Roelof

**Comment by roelof1967** [comment] 2015-01-07 06:34
Of course. 

The hello.js programm looks like this : 

~~~

var Hapi = require('hapi');
    
var server = new Hapi.Server();

server.connection({ port: Number(process.argv[2] || 3000)  });

server.start() ; 

server.route({
  path: '/', method:'GET',
  handler: function handler(request, reply) {
    reply ('Hello hapi'); 
  }
}); 

~~~

The different Linux distro are fedora, pc-bsd on ubuntu by using boxes on nitrious.io 

node version :  v0.10.26    
makemehapi version :  makemehapi@1.0.0 

Roelof

**Comment by lloydbenson** [comment] 2015-01-07 14:34
This is helpful.  Try moving your server.start() after the route.  You are
trying to start it before you've defined it.

**Comment by arb** [comment] 2015-01-07 14:38
As another suggestion, try omitting the port and let hapi just pick the next open port. That messages usually means that port is already in use (probably from a previous run of this code)

**Comment by roelof1967** [comment] 2015-01-07 14:40
I did so my file looks like this : 

~~~

var Hapi = require('hapi');

var server = new Hapi.Server();

server.connection({ port: Number(process.argv[2] || 3000)  });

server.route({
  path: '/', method:'GET',
  handler: function handler(request, reply) {
    reply ('Hello hapi'); 
  }
}); 

server.start() ; 

~~~

When I do node hellohapi.js 3000 I can open my browser and see the text hello hapi.
When I do makemehapi run hellohapi.js I still see this output : 

~~~

makemehapi run hellohapi.js                                                                             
✗ Error connecting to http://localhost:38824: ECONNREFUSED                                                                                                                             
                                                                                                                                                                                       
Error: connect ECONNREFUSED                                                                                                                                                            
    at errnoException (net.js:904:11)                                                                                                                                                  
    at Object.afterConnect [as oncomplete] (net.js:895:19)                         

~~~

**Comment by roelof1967** [comment] 2015-01-07 14:42
@arb 

I did what you said :+1: 

~~~

var Hapi = require('hapi');

var server = new Hapi.Server();

server.route({
  path: '/', method:'GET',
  handler: function handler(request, reply) {
    reply ('Hello hapi'); 
  }
}); 

server.start() ; 
  
~~~

but no difference.

**Comment by arb** [comment] 2015-01-07 14:44
You still need to create a connection:

`server.connections({ host:'localhost' })`

**Comment by roelof1967** [comment] 2015-01-07 14:50
makes no difference

**Comment by lloydbenson** [comment] 2015-01-07 15:29
Out of curiousity have you tried a newer node version?

**Comment by roelof1967** [comment] 2015-01-07 15:40
nope, I have to figure out how to update it on nitrious.io.

**Comment by lloydbenson** [comment] 2015-01-07 15:44
Not sure this is helpful but I have used https://github.com/creationix/nvm
quite a bit for managing node versions.  I'll double check again but I have
fedora 20 at home and I think im at 0.10.32 and I had success.

**Comment by lloydbenson** [comment] 2015-01-07 15:55
I got somewhat close I think to your setup.  I ran 0.10.20 on fedora 18 and
did this exercise with no issues (though it complained alot with hapi 8
required 0.10.32).  I'd also check to see if you have any existing running
processes (ps auxww | grep node) to see if there is a conflict.

**Comment by roelof1967** [comment] 2015-01-07 17:42
Oke, I have a cd of Fedora 21 which I can install. I has version 0.10.33. 
Nitrous.io is a Ubuntu box which has a very old version  :  v0.10.26

The last test I did on the nitroius.io box. 

Roelof

**Comment by roelof1967** [comment] 2015-01-07 17:58
When I try it on C9.io which has version  0.10.33 the same error is displayed.
Schould I install F21 and try locally ?

Roelof

**Comment by lloydbenson** [comment] 2015-01-07 18:07
I don't know anything about nitroius.io or C9.io.  So I can't really
comment on that.  I just know that on both fedora 20 and 18 even with older
versions it seemed to work for me.  I don't think I am going to try to
replicate your exact setup, so I guess its up to you on how much work you
want to do here.  I'd be willing to help a bit more if you just have a
plain OS running a bit newer version so I can at least get closer to the
same setup to try to reproduce.  I can also just leave this open for others
to comment on as well.

**Comment by roelof1967** [comment] 2015-01-07 18:12
Oke, then Im going to install Fedora 21 at test if the new try will work.

**Comment by roelof1967** [comment] 2015-01-07 19:22
On Fedora 21 Workstation I see this output : 

~~~

 makemehapi run test.js
Hello hapi
[roelof@localhost ~]$ makemehapi verify test.js
✗ Error connecting to http://localhost:34617: ECONNREFUSED

Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)

~ ~ ~

**Comment by lloydbenson** [comment] 2015-01-07 19:29
I am at a loss.  I have run this very script and have not run into this
issue.  The only things I can think of are maybe you dont have localhost
defined well in /etc/hosts or selinux is getting in the way etc.  Is there
anything in your messages file?  Also maybe you have some odd hidden chars
in your test.js as well.  Maybe turn hidden chars on just to ensure there
isn't anything weird there.  Sorry for this frustration, have other
workshoppers worked fine for you?

**Comment by roelof1967** [comment] 2015-01-07 20:03
No problem. 

Are you running 64 or 32 bit version ?

I have looked at the systemd journal file but found nothing. 
I have installed only gnome , how can I turm hidden characters on. I have copied the script direct from this page. 

I have no problem so far with javascripting (everything done) , learnyounode(almost done everything) and stream-adventure ( 3 exercises done)

**Comment by lloydbenson** [comment] 2015-01-07 20:40
cat -vT filename should see them.  OS is 64 bit.  What if you copy the
actual solution thats in the directory, same issue?

**Comment by roelof1967** [comment] 2015-01-07 20:48
Very wierd case.

cat -vT gives normal output. 
If I copy the solution then I see the same error as before. 

Pity , we cannot see what verify exactly does. 
and wierd that nodejs hellohapi,js and makemehappi run hellohapi.js does the job.
Only verify breaks. 

It time for me to go sleep,

**Comment by roelof1967** [comment] 2015-01-07 20:54
Found the problem on Fedora. 
The timeout was not changed to 2000. 

On Fedora everything is working fine now.

**Comment by lloydbenson** [comment] 2015-01-07 21:00
Cool.  I will publish that previous fix on master then and see if we have better luck.  I'll do that shortly.  Closing this up but if you have issues afterwards feel free to reopen.

**Closed by lloydbenson** 2015-01-07 21:00 UTC

**Comment by kave** [comment] 2015-01-22 16:31
hmm i'm seeing this same issue on my mac, "node basic.js 55396" starts the server and provides the response as expected.

but using "makemehapi run basic.js" provides this error {"statusCode":404,"error":"Not Found"} due to the server not being able to start.

did you have a chance to push the fix to master?

**Comment by deerawan** [comment] 2015-01-31 11:19
same problem on mac with setup: 
OS: Yosemite 10.10.1
Node: 0.10.33

When I run **makemehapi run exercise1.js**, following error occured

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
✗ Error connecting to http://localhost:54911: ECONNREFUSED

Error: connect ECONNREFUSED
    at errnoException (net.js:904:11)
    at Object.afterConnect [as oncomplete] (net.js:895:19)
```

My code

```
var Hapi = require('hapi');
var server = new Hapi.Server();

server.connection({
	host: 'localhost',
	port: 3110
});

server.route({
	path: '/',
	method: 'GET',
	handler: function(request, reply) {
		reply('Hello Hapi')
	}
});

server.start();
```

It runs perfectly with just **node exercise1.js**. I can see "Hello Hapi" on my browser.

**Comment by KevinBatdorf** [comment] 2015-02-03 08:28
I have the same error as @deerawan with the same OS but node 0.10.24 and only (so far) on the directories exercise. It appears even when i copy the solution directly from the source.

**Comment by KevinBatdorf** [comment] 2015-02-03 09:33
I upgraded to node `v0.10.36` and only receive the following error:
```bash
% makemehapi verify ./exercise4/server.js
✗ Error connecting to http://localhost:38197: ECONNREFUSED

Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```

**Comment by guigros** [comment] 2017-01-24 13:35
Hi everyone,

Just ran into this error today.
I'm using Raspbian on Raspberry.
As "@ghost" mentionned, the problem is coming from the timeout defined in exercise.js, line 50 -> `setTimeout(query.bind(this, mode), 2000);`

Unfortunately, it's the same for each exercise. Would it possible to increase that timeout ?

**Comment by TinaHeiligers** [comment] 2017-06-05 19:07
in 2017, I'm still getting this same error!
It's a pity, I was hoping to use makemehapi to learn hapi quickly. I shall have to research other avenues...
