### ISSUE TITLE
Errors running Handling and Directories exercises

### ISSUE THREAD

**Issue by jbelmont** [hapijs/makemehapi#177] opened 2016-04-02 19:13 UTC
Even with running the solutions to exercise 3, 4, and 5 I am getting errors with the makemehapi nodeschool workshopper.

**Comment by Shawful** [comment] 2016-04-06 01:33
Same.  I experience the following error:

ReferenceError: server is not defined
    at Object.<anonymous> (/Users/shawnshaw/Desktop/git/makemehapi/handling/handling.js:3:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
✗ Error connecting to http://localhost:54713: ECONNREFUSED
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:54713
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)

**Comment by fiveisprime** [comment] 2016-04-06 13:03
I'm unable to reproduce the errors for 3-5, can you give me some information about your environment? OS, Node version, npm version?

The port being in use is a bit of a fluke. :/

**Comment by jbelmont** [comment] 2016-04-06 13:28
node version 4.2.4, npm version 2.14.12, OS X El Capitan 10.11.14
I am running these exercises on ITERM 2 as well

**Comment by fiveisprime** [comment] 2016-04-06 14:49
What is the actual error that you see?

**Comment by fiveisprime** [comment] 2016-09-06 18:01
I'm going to close this, but if you want to dig back into this I'm up for it.

It looks like the `server` variable was mistyped (it's possibly `Server`), which caused the error. Either way, this isn't an issue with the module.

Again, I'm happy to help out if you still need it.

**Closed by fiveisprime** 2016-09-06 18:01 UTC
