### ISSUE TITLE
403 error with module 3 : handling

### ISSUE THREAD

**Issue by Vestibule** [hapijs/makemehapi#185] opened 2016-12-02 14:08 UTC
Hi there !

I am having trouble with the third module.
It runs without any error when I type `node program.js`, when I try `makemehapi run progam.js`, it outputs the html. But when I do `makemehapi verify program.js` it print "Status code 403 returned from url http://localhost:55487, expected 200."

I'm running last Linux Mint. node v6.9.1, npm 3.10.8.

I hope we can work it out :)
 
Thanks in advance for the help I'll have.

**Comment by vfonic** [comment] 2016-12-04 06:35
👍  I'm also having the same problem.

**Comment by fiveisprime** [comment] 2016-12-06 00:44
What do you have for the solution? I can't seem to recreate this.

**Comment by alanbhamilton** [comment] 2016-12-06 03:05
I'm also having this problem. It appears that the solution process is returning the 403 as I'm logging my uri in the line before the fail is logged.
```
Server running at http://localhost:63192
✗ Status code 403 returned from url http://localhost:63193, expected 200.
```

**Comment by vfonic** [comment] 2016-12-06 16:05
@fiveisprime I tried several different solutions, both with relative and absolute paths, but nothing worked.

Here's my solution that's committed in a git repo:
`src/server/index.js`:
```js
import hapi from 'hapi';
import inert from 'inert';
import path from 'path';

const server = new hapi.Server();

server.register(inert, function (err) {
  if (err) { throw err; }
});

server.connection({
  host: 'localhost',
  port: Number(process.argv[2] || 9000)
});

server.route({
  method: 'GET',
  path: '/',
  handler: {
    file: path.join(__dirname, '../../dist/index.html')
  }
});

server.start(function(err) {
  if (err) { throw err; }
  console.log('Server running at: ' + server.info.uri);
  console.log(path.join(__dirname, '../../dist/index.html'));
});
```

`dist/index.html`:
```html
<!doctype html>
<html>
  <head><title>Hello Handling</title></head>
  <body>
    Hello Handling
  </body>
</html>
```

Gulp/babel generated `lib/server/index.js`:
```js
'use strict';

var _hapi = require('hapi');

var _hapi2 = _interopRequireDefault(_hapi);

var _inert = require('inert');

var _inert2 = _interopRequireDefault(_inert);

var _path = require('path');

var _path2 = _interopRequireDefault(_path);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var server = new _hapi2.default.Server();

server.register(_inert2.default, function (err) {
  if (err) {
    throw err;
  }
});

server.connection({
  host: 'localhost',
  port: Number(process.argv[2] || 9000)
});

server.route({
  method: 'GET',
  path: '/',
  handler: {
    file: _path2.default.join(__dirname, '../../dist/index.html')
  }
});

server.start(function (err) {
  if (err) {
    throw err;
  }
  console.log('Server running at: ' + server.info.uri);
  console.log(_path2.default.join(__dirname, '../../dist/index.html'));
});
```

Starting the server with:
`$ node lib/server/index.js`

Going to `http://localhost:9000` properly shows the HTML file.

PS if it's worth noting, the following exercise (directories) works.

**Comment by fiveisprime** [comment] 2016-12-06 16:28
Please run `$ npm ls --depth 0` within your working directory and paste the result. I want to compare the versions of each module to see if maybe there's something there.

**Comment by vfonic** [comment] 2016-12-06 16:45
```sh
[~/MEGAsync/Developer/JavaScript/makemehapi]$ npm ls --depth 0                                                                                                                          *[4ecfcf6][ruby-2.3.0]
/Users/viktorfonic/MEGAsync/Developer/JavaScript/makemehapi
├── babel-eslint@7.1.1
├── babel-loader@6.2.8
├── babel-polyfill@6.16.0
├── babel-preset-latest@6.16.0
├── babel-preset-react@6.16.0
├── del@2.2.2
├── eslint@3.11.1
├── eslint-config-airbnb@13.0.0
├── eslint-plugin-import@2.2.0
├── UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@3.0.1
├── eslint-plugin-react@6.7.1
├── gulp@3.9.1
├── gulp-babel@6.1.2
├── gulp-eslint@3.0.1
├── hapi@16.0.1
├── inert@4.0.3
├── node-pre-gyp@0.6.32 extraneous
├── vision@4.1.1 extraneous
└── webpack-stream@3.2.0

npm ERR! peer dep missing: eslint-plugin-jsx-a11y@^2.2.3, required by eslint-config-airbnb@13.0.0
npm ERR! extraneous: node-pre-gyp@0.6.32 /Users/viktorfonic/MEGAsync/Developer/JavaScript/makemehapi/node_modules/node-pre-gyp
npm ERR! extraneous: vision@4.1.1 /Users/viktorfonic/MEGAsync/Developer/JavaScript/makemehapi/node_modules/vision
```

Note: I'm currently not using eslint package.

**Comment by vfonic** [comment] 2016-12-06 16:46
I can paste the gulp/webpack conf that I'm using as well.

**Comment by alanbhamilton** [comment] 2016-12-06 18:27
I'm fairly sure this issue has to do with the confine option that confines file responses in the Inert plugin. I don't really understand the exact reason why but it appears the confine option defaults to true and it's causing Inert to generate the 403 when excercise.js spins up the server and checks solution.js

I cloned the makemehapi repo and changed the solution route handler from
```
handler: {
    file: Path.join(__dirname, 'index.html')
}
```
to
```
handler: (request, reply) => {
    reply.file(Path.join(__dirname, 'index.html'), { confine: false }); // disable sec feature
}
```
My directory structure:
```
☁  mmh  ls
handling         makemehapi-master
```
Then from my project directory (handling):
`☁  handling  node ../makemehapi-master/makemehapi.js verify index.js`

I now get a pass from my solution from the verify.

My index.js reference:
```
var Hapi = require('hapi');
var Inert = require('inert');
var Path = require('path');

var server = new Hapi.Server();

server.connection({
  host: 'localhost',
  port: Number(process.argv[2] || 8080)
});

server.register(Inert, (err) => {
  if (err) throw err;

  server.route({
    path: '/',
    method: 'GET',
    handler: (request, reply) => {
      reply.file(Path.join(__dirname, 'index.html'));
    }
  });
});

server.start((err) => {
  if (err) throw err;
  console.log(`Server running at ${server.info.uri}`);
});
```
@fiveisprime:
```
☁  handling  npm ls --depth 0
handling@1.0.0 /Users/alan/Downloads/mmh/handling
├── hapi@16.0.1
└── inert@4.0.3
```

**Comment by alanbhamilton** [comment] 2016-12-06 19:34
Confine was added to Inert as of v4.0.0 according to the [release notes](https://github.com/hapijs/inert/issues/62) as a security measure.

**Comment by fiveisprime** [comment] 2016-12-06 22:38
Thanks for the info, I'll get the solution changed.

I'm still unsure why I can't seem to recreate this - maybe because I'm on Windows today?

**Comment by alanbhamilton** [comment] 2016-12-06 22:50
Ok, I think I have a handle on this now.

The problem is that Inert >4.0.0 will not serve files outside it's files.relativeTo path.

Release notes:
> Directly serving files outside the files.relativeTo path returns a 403 response instead of the file contents.

And when files.relativeTo is not explicitly set it defaults to "." So when we're running makemehapi from our project directory the hapi server started to run solution.js is winding up with it's relativeTo path set to our project folder, not __dirname like it should be.

So far I think just adding this code to solution.js looks like a good solution:
```
var server = new Hapi.Server({
  connections: {
    routes: {
      files: {
        relativeTo: __dirname
      }
    }
  }
});
```

**Closed** 2016-12-08 00:06 UTC
